variable "aws_region" {}
variable "vpc_cidr" {}
variable "vpc_name" {}
variable "IGW_name" {}
variable "key_name" {}
variable "public_subnet1_cidr" {}
variable "public_subnet1_name" {}
variable Main_Routing_Table {}
variable "azs" {}
variable "environment" {}
variable "instance_type" {}
